import { Announcement, EducationalStage } from '../models';

export const MOCK_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-01',
    title: 'إجازة نصف العام',
    content: 'نعلن لجميع الطلاب عن إجازة نصف العام من الأحد القادم، مع استمرار توفر جميع الفيديوهات والملفات على المنصة.',
    targetStage: 'all',
    publishDate: '2026-06-01',
    createdAt: '2026-06-01',
  },
  {
    id: 'ann-02',
    title: 'امتحان غدًا - أولى إعدادي',
    content: 'تذكير بامتحان النحو غدًا الساعة 5 مساءً. يرجى مراجعة ملزمة المبتدأ والخبر قبل الامتحان.',
    targetStage: EducationalStage.PrepFirst,
    publishDate: '2026-06-14',
    createdAt: '2026-06-14',
  },
  {
    id: 'ann-03',
    title: 'تم رفع شرح جديد - نائب الفاعل',
    content: 'تم رفع فيديو شرح جديد لدرس نائب الفاعل، يرجى مشاهدته قبل حل الواجب.',
    targetStage: EducationalStage.PrepSecond,
    publishDate: '2026-06-02',
    createdAt: '2026-06-02',
  },
  {
    id: 'ann-04',
    title: 'تم رفع ملف PDF جديد - الممنوع من الصرف',
    content: 'تم إضافة ملزمة شاملة عن الممنوع من الصرف في قسم مكتبة PDF الخاص بمرحلتكم.',
    targetStage: EducationalStage.PrepThird,
    publishDate: '2026-06-05',
    createdAt: '2026-06-05',
  },
  {
    id: 'ann-05',
    title: 'موعد امتحان الحال والتمييز',
    content: 'سيُعقد امتحان الحال والتمييز يوم الخميس القادم، الامتحان متاح الآن على المنصة.',
    targetStage: EducationalStage.SecondaryFirst,
    publishDate: '2026-06-13',
    createdAt: '2026-06-13',
  },
  {
    id: 'ann-06',
    title: 'بدء المراجعة النهائية',
    content: 'تبدأ حصص المراجعة النهائية لطلاب الثانوية العامة الأسبوع القادم، تابعوا جدول الحصص على المنصة.',
    targetStage: EducationalStage.SecondarySecond,
    publishDate: '2026-06-20',
    createdAt: '2026-06-20',
  },
  {
    id: 'ann-07',
    title: 'تحديث على واجهة المنصة',
    content: 'قمنا بإضافة تحسينات جديدة على لوحة التحكم الخاصة بالطالب لتسهيل متابعة التقدم الدراسي.',
    targetStage: 'all',
    publishDate: '2026-06-22',
    createdAt: '2026-06-22',
  },
  {
    id: 'ann-08',
    title: 'تذكير بتسليم واجب البلاغة',
    content: 'آخر موعد لتسليم واجب البلاغة (التشبيه) هو نهاية هذا الأسبوع.',
    targetStage: EducationalStage.PrepFirst,
    publishDate: '2026-06-25',
    createdAt: '2026-06-25',
  },
];
