import { EducationalStage, Exam } from '../models';

export const MOCK_EXAMS: Exam[] = [
  {
    id: 'exam-01',
    title: 'امتحان شهر يونيو - النحو',
    stage: EducationalStage.PrepFirst,
    questionCount: 20,
    durationMinutes: 40,
    totalMarks: 20,
    status: 'published',
    createdAt: '2026-06-10',
  },
  {
    id: 'exam-02',
    title: 'اختبار قصير - البلاغة',
    stage: EducationalStage.PrepFirst,
    questionCount: 10,
    durationMinutes: 15,
    totalMarks: 10,
    status: 'draft',
    createdAt: '2026-06-20',
  },
  {
    id: 'exam-03',
    title: 'امتحان الشهر - نائب الفاعل والإضافة',
    stage: EducationalStage.PrepSecond,
    questionCount: 25,
    durationMinutes: 45,
    totalMarks: 25,
    status: 'published',
    createdAt: '2026-06-11',
  },
  {
    id: 'exam-04',
    title: 'امتحان تجميعي - الأدب العباسي',
    stage: EducationalStage.PrepSecond,
    questionCount: 15,
    durationMinutes: 30,
    totalMarks: 15,
    status: 'published',
    createdAt: '2026-06-22',
  },
  {
    id: 'exam-05',
    title: 'امتحان الممنوع من الصرف وأسلوب الشرط',
    stage: EducationalStage.PrepThird,
    questionCount: 30,
    durationMinutes: 50,
    totalMarks: 30,
    status: 'published',
    createdAt: '2026-06-12',
  },
  {
    id: 'exam-06',
    title: 'اختبار البلاغة - الاستعارة',
    stage: EducationalStage.PrepThird,
    questionCount: 12,
    durationMinutes: 20,
    totalMarks: 12,
    status: 'draft',
    createdAt: '2026-06-23',
  },
  {
    id: 'exam-07',
    title: 'امتحان الحال والتمييز',
    stage: EducationalStage.SecondaryFirst,
    questionCount: 22,
    durationMinutes: 40,
    totalMarks: 22,
    status: 'published',
    createdAt: '2026-06-13',
  },
  {
    id: 'exam-08',
    title: 'اختبار العروض والنقد الأدبي',
    stage: EducationalStage.SecondaryFirst,
    questionCount: 18,
    durationMinutes: 35,
    totalMarks: 18,
    status: 'published',
    createdAt: '2026-06-24',
  },
  {
    id: 'exam-09',
    title: 'امتحان أسلوب التوكيد',
    stage: EducationalStage.SecondarySecond,
    questionCount: 20,
    durationMinutes: 35,
    totalMarks: 20,
    status: 'published',
    createdAt: '2026-06-14',
  },
  {
    id: 'exam-10',
    title: 'امتحان تجريبي شامل - نهاية الفصل',
    stage: EducationalStage.SecondarySecond,
    questionCount: 40,
    durationMinutes: 60,
    totalMarks: 40,
    status: 'published',
    createdAt: '2026-06-26',
  },
];
