import { EducationalStage, PdfFile } from '../models';

export const MOCK_PDFS: PdfFile[] = [
  {
    id: 'pdf-01',
    title: 'ملخص المبتدأ والخبر',
    description: 'ملزمة شاملة لقاعدة المبتدأ والخبر مع تدريبات محلولة.',
    stage: EducationalStage.PrepFirst,
    fileUrl: '',
    uploadDate: '2026-06-02',
    downloadCount: 154,
  },
  {
    id: 'pdf-02',
    title: 'بنك أسئلة البلاغة - الصف الأول الإعدادي',
    description: 'مجموعة أسئلة متنوعة على التشبيه بأنواعه.',
    stage: EducationalStage.PrepFirst,
    fileUrl: '',
    uploadDate: '2026-06-09',
    downloadCount: 98,
  },
  {
    id: 'pdf-03',
    title: 'ملزمة نائب الفاعل والإضافة',
    description: 'شرح مكثف مع تمارين تفاعلية على البابين.',
    stage: EducationalStage.PrepSecond,
    fileUrl: '',
    uploadDate: '2026-06-04',
    downloadCount: 121,
  },
  {
    id: 'pdf-04',
    title: 'خريطة الأدب العباسي الذهنية',
    description: 'خريطة ذهنية شاملة لأهم أعلام العصر العباسي.',
    stage: EducationalStage.PrepSecond,
    fileUrl: '',
    uploadDate: '2026-06-15',
    downloadCount: 76,
  },
  {
    id: 'pdf-05',
    title: 'دليل الممنوع من الصرف الشامل',
    description: 'جميع حالات الممنوع من الصرف في جدول واحد.',
    stage: EducationalStage.PrepThird,
    fileUrl: '',
    uploadDate: '2026-06-05',
    downloadCount: 203,
  },
  {
    id: 'pdf-06',
    title: 'تدريبات أسلوب الشرط',
    description: '50 سؤال محلول على أسلوب الشرط بأدواته المختلفة.',
    stage: EducationalStage.PrepThird,
    fileUrl: '',
    uploadDate: '2026-06-12',
    downloadCount: 142,
  },
  {
    id: 'pdf-07',
    title: 'ملزمة الحال والتمييز',
    description: 'أمثلة موسعة وتدريبات على الفروق بين الحال والتمييز.',
    stage: EducationalStage.SecondaryFirst,
    fileUrl: '',
    uploadDate: '2026-06-06',
    downloadCount: 187,
  },
  {
    id: 'pdf-08',
    title: 'قواعد العروض المبسطة',
    description: 'شرح مبسط لتقطيع الأبيات الشعرية وأوزانها.',
    stage: EducationalStage.SecondaryFirst,
    fileUrl: '',
    uploadDate: '2026-06-20',
    downloadCount: 88,
  },
  {
    id: 'pdf-09',
    title: 'ملخص أسلوب التوكيد',
    description: 'ملزمة مركزة على أسلوب التوكيد بنوعيه اللفظي والمعنوي.',
    stage: EducationalStage.SecondarySecond,
    fileUrl: '',
    uploadDate: '2026-06-07',
    downloadCount: 165,
  },
  {
    id: 'pdf-10',
    title: 'مراجعة نهائية - نماذج امتحانات',
    description: 'نماذج امتحانات سابقة محلولة لمراجعة شاملة قبل الثانوية العامة.',
    stage: EducationalStage.SecondarySecond,
    fileUrl: '',
    uploadDate: '2026-06-24',
    downloadCount: 231,
  },
];
