import { EducationalStage } from '../models';
import { Student } from '../models';

export const MOCK_STUDENTS: Student[] = [
  {
    id: 'stu-01',
    studentName: 'يوسف أحمد كامل',
    parentName: 'أحمد كامل السيد',
    studentPhone: '01012345601',
    parentPhone: '01123456701',
    email: 'yousef.ahmed@student.mock',
    stage: EducationalStage.PrepFirst,
    gender: 'male',
    governorate: 'القاهرة',
    city: 'المعادي',
    status: 'active',
    progressPercent: 72,
    averageScore: 84,
    completedLessons: 18,
    createdAt: '2026-01-12',
  },
  {
    id: 'stu-02',
    studentName: 'مريم محمد سعيد',
    parentName: 'محمد سعيد عبدالله',
    studentPhone: '01012345602',
    parentPhone: '01123456702',
    email: 'mariam.mohamed@student.mock',
    stage: EducationalStage.PrepFirst,
    gender: 'female',
    governorate: 'الجيزة',
    city: 'الدقي',
    status: 'active',
    progressPercent: 88,
    averageScore: 91,
    completedLessons: 22,
    createdAt: '2026-01-20',
  },
  {
    id: 'stu-03',
    studentName: 'عمر خالد فتحي',
    parentName: 'خالد فتحي إبراهيم',
    studentPhone: '01012345603',
    parentPhone: '01123456703',
    email: 'omar.khaled@student.mock',
    stage: EducationalStage.PrepFirst,
    gender: 'male',
    governorate: 'الإسكندرية',
    city: 'سيدي جابر',
    status: 'inactive',
    progressPercent: 34,
    averageScore: 61,
    completedLessons: 7,
    createdAt: '2026-02-02',
  },
  {
    id: 'stu-04',
    studentName: 'سلمى طارق عبدالله',
    parentName: 'طارق عبدالله منصور',
    studentPhone: '01012345604',
    parentPhone: '01123456704',
    email: 'salma.tarek@student.mock',
    stage: EducationalStage.PrepSecond,
    gender: 'female',
    governorate: 'القاهرة',
    city: 'مدينة نصر',
    status: 'active',
    progressPercent: 65,
    averageScore: 78,
    completedLessons: 15,
    createdAt: '2026-02-10',
  },
  {
    id: 'stu-05',
    studentName: 'أحمد إبراهيم الشريف',
    parentName: 'إبراهيم الشريف حسن',
    studentPhone: '01012345605',
    parentPhone: '01123456705',
    email: 'ahmed.ibrahim@student.mock',
    stage: EducationalStage.PrepSecond,
    gender: 'male',
    governorate: 'الشرقية',
    city: 'الزقازيق',
    status: 'active',
    progressPercent: 55,
    averageScore: 70,
    completedLessons: 12,
    createdAt: '2026-02-18',
  },
  {
    id: 'stu-06',
    studentName: 'نور الدين حسن',
    parentName: 'حسن محمود عثمان',
    studentPhone: '01012345606',
    parentPhone: '01123456706',
    email: 'nour.hassan@student.mock',
    stage: EducationalStage.PrepThird,
    gender: 'male',
    governorate: 'الجيزة',
    city: 'فيصل',
    status: 'active',
    progressPercent: 91,
    averageScore: 95,
    completedLessons: 30,
    createdAt: '2026-03-01',
  },
  {
    id: 'stu-07',
    studentName: 'هنا عادل منصور',
    parentName: 'عادل منصور فؤاد',
    studentPhone: '01012345607',
    parentPhone: '01123456707',
    email: 'hana.adel@student.mock',
    stage: EducationalStage.PrepThird,
    gender: 'female',
    governorate: 'الدقهلية',
    city: 'المنصورة',
    status: 'active',
    progressPercent: 80,
    averageScore: 88,
    completedLessons: 25,
    createdAt: '2026-03-09',
  },
  {
    id: 'stu-08',
    studentName: 'زياد وليد عزت',
    parentName: 'وليد عزت الديب',
    studentPhone: '01012345608',
    parentPhone: '01123456708',
    email: 'ziad.waleed@student.mock',
    stage: EducationalStage.PrepThird,
    gender: 'male',
    governorate: 'القليوبية',
    city: 'بنها',
    status: 'suspended',
    progressPercent: 20,
    averageScore: 48,
    completedLessons: 4,
    createdAt: '2026-03-15',
  },
  {
    id: 'stu-09',
    studentName: 'جنى محمود فؤاد',
    parentName: 'محمود فؤاد راضي',
    studentPhone: '01012345609',
    parentPhone: '01123456709',
    email: 'jana.mahmoud@student.mock',
    stage: EducationalStage.SecondaryFirst,
    gender: 'female',
    governorate: 'القاهرة',
    city: 'التجمع الخامس',
    status: 'active',
    progressPercent: 76,
    averageScore: 86,
    completedLessons: 20,
    createdAt: '2026-04-05',
  },
  {
    id: 'stu-10',
    studentName: 'كريم سامي رزق',
    parentName: 'سامي رزق الديب',
    studentPhone: '01012345610',
    parentPhone: '01123456710',
    email: 'kareem.samy@student.mock',
    stage: EducationalStage.SecondaryFirst,
    gender: 'male',
    governorate: 'الجيزة',
    city: 'الشيخ زايد',
    status: 'active',
    progressPercent: 60,
    averageScore: 74,
    completedLessons: 14,
    createdAt: '2026-04-14',
  },
  {
    id: 'stu-11',
    studentName: 'ملك أشرف نبيل',
    parentName: 'أشرف نبيل شعبان',
    studentPhone: '01012345611',
    parentPhone: '01123456711',
    email: 'malak.ashraf@student.mock',
    stage: EducationalStage.SecondarySecond,
    gender: 'female',
    governorate: 'الإسكندرية',
    city: 'سموحة',
    status: 'active',
    progressPercent: 94,
    averageScore: 97,
    completedLessons: 34,
    createdAt: '2026-05-02',
  },
  {
    id: 'stu-12',
    studentName: 'عبدالرحمن جمال توفيق',
    parentName: 'جمال توفيق سالم',
    studentPhone: '01012345612',
    parentPhone: '01123456712',
    email: 'abdelrahman.gamal@student.mock',
    stage: EducationalStage.SecondarySecond,
    gender: 'male',
    governorate: 'المنوفية',
    city: 'شبين الكوم',
    status: 'inactive',
    progressPercent: 42,
    averageScore: 63,
    completedLessons: 9,
    createdAt: '2026-05-20',
  },
];
