import { EducationalStage, Video } from '../models';

export const MOCK_VIDEOS: Video[] = [
  {
    id: 'vid-01',
    title: 'المبتدأ والخبر - الدرس الأول',
    description: 'شرح مبسّط لأنواع المبتدأ والخبر مع أمثلة تطبيقية وتدريبات.',
    thumbnailUrl: '',
    stage: EducationalStage.PrepFirst,
    lessonName: 'النحو: المبتدأ والخبر',
    durationMinutes: 28,
    status: 'published',
    teacherName: 'محمد بكر',
    createdAt: '2026-06-01',
    watchCount: 412,
  },
  {
    id: 'vid-02',
    title: 'التشبيه في البلاغة العربية',
    description: 'أركان التشبيه وأنواعه مع تحليل نماذج من الشعر العربي.',
    thumbnailUrl: '',
    stage: EducationalStage.PrepFirst,
    lessonName: 'البلاغة: التشبيه',
    durationMinutes: 24,
    status: 'published',
    teacherName: 'محمد بكر',
    createdAt: '2026-06-05',
    watchCount: 356,
  },
  {
    id: 'vid-03',
    title: 'تحليل نص أدبي - الفصل الأول',
    description: 'تدريب على استخراج الأفكار الرئيسية والقيم من نص أدبي.',
    thumbnailUrl: '',
    stage: EducationalStage.PrepFirst,
    lessonName: 'القراءة: النص الأدبي',
    durationMinutes: 20,
    status: 'draft',
    teacherName: 'محمد بكر',
    createdAt: '2026-06-10',
    watchCount: 0,
  },
  {
    id: 'vid-04',
    title: 'نائب الفاعل وأحكامه',
    description: 'كيفية تحويل الفعل المبني للمجهول واستخراج نائب الفاعل.',
    thumbnailUrl: '',
    stage: EducationalStage.PrepSecond,
    lessonName: 'النحو: نائب الفاعل',
    durationMinutes: 26,
    status: 'published',
    teacherName: 'محمد بكر',
    createdAt: '2026-06-02',
    watchCount: 298,
  },
  {
    id: 'vid-05',
    title: 'الإضافة اللفظية والمعنوية',
    description: 'الفرق بين الإضافة اللفظية والمعنوية بأمثلة موسعة.',
    thumbnailUrl: '',
    stage: EducationalStage.PrepSecond,
    lessonName: 'النحو: الإضافة',
    durationMinutes: 22,
    status: 'published',
    teacherName: 'محمد بكر',
    createdAt: '2026-06-08',
    watchCount: 271,
  },
  {
    id: 'vid-06',
    title: 'ملامح العصر العباسي الأدبية',
    description: 'أبرز شعراء وأدباء العصر العباسي وخصائص أدبهم.',
    thumbnailUrl: '',
    stage: EducationalStage.PrepSecond,
    lessonName: 'الأدب: العصر العباسي',
    durationMinutes: 30,
    status: 'draft',
    teacherName: 'محمد بكر',
    createdAt: '2026-06-14',
    watchCount: 0,
  },
  {
    id: 'vid-07',
    title: 'الممنوع من الصرف - القاعدة الكاملة',
    description: 'كل حالات الممنوع من الصرف مع جدول تلخيصي وتدريبات.',
    thumbnailUrl: '',
    stage: EducationalStage.PrepThird,
    lessonName: 'النحو: الممنوع من الصرف',
    durationMinutes: 32,
    status: 'published',
    teacherName: 'محمد بكر',
    createdAt: '2026-06-03',
    watchCount: 389,
  },
  {
    id: 'vid-08',
    title: 'أسلوب الشرط وأدواته',
    description: 'أدوات الشرط الجازمة وغير الجازمة مع الإعراب.',
    thumbnailUrl: '',
    stage: EducationalStage.PrepThird,
    lessonName: 'النحو: أسلوب الشرط',
    durationMinutes: 27,
    status: 'published',
    teacherName: 'محمد بكر',
    createdAt: '2026-06-11',
    watchCount: 244,
  },
  {
    id: 'vid-09',
    title: 'الاستعارة التصريحية والمكنية',
    description: 'الفرق بين أنواع الاستعارة مع أمثلة من القرآن والشعر.',
    thumbnailUrl: '',
    stage: EducationalStage.PrepThird,
    lessonName: 'البلاغة: الاستعارة',
    durationMinutes: 25,
    status: 'published',
    teacherName: 'محمد بكر',
    createdAt: '2026-06-17',
    watchCount: 301,
  },
  {
    id: 'vid-10',
    title: 'الحال والتمييز - الفروق والأحكام',
    description: 'التمييز بين الحال والتمييز مع نماذج امتحانات سابقة.',
    thumbnailUrl: '',
    stage: EducationalStage.SecondaryFirst,
    lessonName: 'النحو: الحال والتمييز',
    durationMinutes: 33,
    status: 'published',
    teacherName: 'محمد بكر',
    createdAt: '2026-06-04',
    watchCount: 512,
  },
  {
    id: 'vid-11',
    title: 'بحور الشعر - البحر الطويل والبسيط',
    description: 'التفعيلات وتقطيع الأبيات الشعرية خطوة بخطوة.',
    thumbnailUrl: '',
    stage: EducationalStage.SecondaryFirst,
    lessonName: 'العروض: البحور الشعرية',
    durationMinutes: 29,
    status: 'draft',
    teacherName: 'محمد بكر',
    createdAt: '2026-06-19',
    watchCount: 0,
  },
  {
    id: 'vid-12',
    title: 'مدخل إلى النقد الأدبي الحديث',
    description: 'أهم مدارس النقد الأدبي وتطبيقاتها على نصوص مختارة.',
    thumbnailUrl: '',
    stage: EducationalStage.SecondaryFirst,
    lessonName: 'النقد الأدبي',
    durationMinutes: 31,
    status: 'published',
    teacherName: 'محمد بكر',
    createdAt: '2026-06-21',
    watchCount: 187,
  },
  {
    id: 'vid-13',
    title: 'أسلوب التوكيد بنوعيه',
    description: 'التوكيد اللفظي والمعنوي وأدواته مع تدريبات إعرابية.',
    thumbnailUrl: '',
    stage: EducationalStage.SecondarySecond,
    lessonName: 'النحو: أسلوب التوكيد',
    durationMinutes: 24,
    status: 'published',
    teacherName: 'محمد بكر',
    createdAt: '2026-06-06',
    watchCount: 445,
  },
  {
    id: 'vid-14',
    title: 'اتجاهات الأدب العربي الحديث',
    description: 'أبرز الاتجاهات الأدبية في العصر الحديث وروادها.',
    thumbnailUrl: '',
    stage: EducationalStage.SecondarySecond,
    lessonName: 'الأدب الحديث',
    durationMinutes: 28,
    status: 'published',
    teacherName: 'محمد بكر',
    createdAt: '2026-06-16',
    watchCount: 398,
  },
  {
    id: 'vid-15',
    title: 'مراجعة نهائية شاملة - الجزء الأول',
    description: 'مراجعة عامة على أهم أبواب النحو والبلاغة قبل الامتحان.',
    thumbnailUrl: '',
    stage: EducationalStage.SecondarySecond,
    lessonName: 'مراجعة نهائية',
    durationMinutes: 45,
    status: 'draft',
    teacherName: 'محمد بكر',
    createdAt: '2026-06-25',
    watchCount: 0,
  },
];
